name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.MY_EC2_KEY }}
          source: /Users/mac/Documents/MY-URL  # All files in the MY-URL directory
          target: "/home/ec2-user/MY-URL"  # Target path on EC2
