name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0  # Use a stable version

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Set up SSH key
        run: |
          echo "${{ secrets.MY_EC2_KEY }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem -r ./MY-URL ec2-user@98.83.25.31:/var/www/html
